apiVersion: v1
kind: Namespace
metadata:
  name: pacman-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
    app.kubernetes.io/name: pacman
  name: mongo
  namespace: pacman-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
      app.kubernetes.io/name: pacman
  template:
    metadata:
      labels:
        name: mongo
        app.kubernetes.io/name: pacman
    spec:
      nodeName: ip-192-168-17-167.ec2.internal
      securityContext:
        fsGroup: 1001
      initContainers:
      - name: fix-perms
        image: busybox:1.36
        command: ["sh", "-c", "chown -R 1001:1001 /bitnami/mongodb"]
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: mongo-db
            mountPath: /bitnami/mongodb
      containers:
      - image: bitnamilegacy/mongodb:5.0.10
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /bitnami/mongodb
      volumes:
        - name: mongo-db
          hostPath:
            path: /var/lib/pacman-mongo
            type: DirectoryOrCreate
